### ISSUE TITLE
feature: add playbook run pre-requisites checks

### ISSUE THREAD

**Issue by mzsrtgzr2** [cocmd/cocmd#18]
add to cocmd.yaml automations a section for pre_requiresites with conditions that should be met on this machine.
for example:
- missing a command (docker, node etc)
- missing system requirements - gpu, memory, etc

each pre_requisite should have some actionable (like installing a cocmd package or run a command line to fix it).

**Comment by mzsrtgzr2** [comment]
this is required because this is recuring many times:
```yaml

- title: install node if needed
          approval_message: Ready to start?
          runner: shell
          content: |
            # if node not installed, run cocmd install node.setup
            if ! node -v &> /dev/null
            then
              echo "node not installed"
              cocmd --no-verbose install node.setup
            fi

            # if yarn not installed, run cocmd install yarn.setup
            if ! yarn -v &> /dev/null
            then
              echo "yarn not installed"
              cocmd --no-verbose install node.yarn.setup
            fi

```

i think that the logic of checking if something happens (for example, command exists or not) and running a setup `cocmd install` after , I did it many times know and its just boilerplate.

we can do something like this:

```yaml
name: cocmd
automations:
  - name: web
    content:
      description: start the website
      env: osx
      requires:
            - node.setup
            - python.setup
      steps: ...      
```

and adding to playbook a `check` field
```yaml
name: node
automations:
  - name: setup
    content:
      description: "Setup common development tools on macOS"
      env: osx
      check: |
         if ! node -v > /dev/null; then
            exit 1
          fi
      steps: ...
```
