### ISSUE TITLE
feature: create step runner for git.hook-xxx

### ISSUE THREAD

**Issue by mzsrtgzr2** [cocmd/cocmd#92]
**Description**

adding git hooks should be pretty straightforward and easy

instead of doing this with shell runner:
```yaml
- title: add git hooks
  description: pre-commit and pre-push hooks for rust fmt and clippy
  runner: shell
  content: |
    cd my-project
    touch .git/hooks/pre-commit
    chmod +x .git/hooks/pre-commit

    cat << 'EOF' > .git/hooks/pre-commit
    #!/bin/bash
    cargo clippy --fix --allow-dirty
    cargo fmt
    cargo fix --allow-dirty 

    # Add any changes made by the formatting commands
    git add .
    EOF

    echo "pre-push hook added"
    cat .git/hooks/pre-commit

    touch .git/hooks/pre-push
    chmod +x .git/hooks/pre-push
    
    cat << 'EOF' > .git/hooks/pre-push
    #!/bin/bash
    cargo clippy
    EOF

    echo "pre-push hook added"
    cat .git/hooks/pre-push
```

let's create the following runner type: git-hook
in the new field 'to' we recieve the git hook type as in this documentation: https://git-scm.com/docs/githooks
the content contains the file to be written (bash syntax).
for example:

```yaml
- title: add git hooks
  description: pre-commit and pre-push hooks for rust fmt and clippy
  runner: git-hook
  to: pre-commit
  workdir:  my-project
  content: |
    #!/bin/bash
    cargo clippy --fix --allow-dirty
    cargo fmt
    cargo fix --allow-dirty 
    git add .
```

**tests**
create a test for it. make sure that the .git hook files are created correctly.

**Docs**
create a documentaiton for how to add easily git hook as a step in playbooks
