### ISSUE TITLE
feature: step flag to quit playbook on fail

### ISSUE THREAD

**Issue by mzsrtgzr2** [cocmd/cocmd#96]
**Description**
add a step attribute (yaml) to stop the playbook on fail.
for example:
```yaml
steps:
 - title: do something
   runner: shell
   stop_on_fail: true
   content: |
     exit 1
```

this step should stop the playbook.
output to the cli should:
`step "do something" failed and stopped the playbook without finishing"

**Tests**
test the flow with dummy playbook and different flag values

**Docs**
add flag documentation to website
